pipeline {
    agent any

    environment {
        ASPNETCORE_ENVIRONMENT = 'Production'
        DOCKER_IMAGE_NAME = 'backend-serkan'
        DOCKER_REGISTRY_CREDENTIALS = 'dockerhub-credentials' // Jenkins Credential ID for Docker Hub
    }

    stages {
        stage('Checkout') {
            steps {
                // Check out the source code from the Git repository
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Install .NET SDK without sudo
                    sh 'wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh'
                    sh 'chmod +x /tmp/dotnet-install.sh'
                    sh '/tmp/dotnet-install.sh --version 3.1 --install-dir /var/lib/jenkins/tools/dotnet'

                    // .NET Restore, Build, and Publish
                    sh '/var/lib/jenkins/tools/dotnet/dotnet restore src/Web/RealEstate.WebAPI/RealEstate.WebAPI.csproj'
                    sh '/var/lib/jenkins/tools/dotnet/dotnet build src/Web/RealEstate.WebAPI/RealEstate.WebAPI.csproj -c Release -o /app/build'
                    sh '/var/lib/jenkins/tools/dotnet/dotnet publish src/Web/RealEstate.WebAPI/RealEstate.WebAPI.csproj -c Release -o /app/publish /p:UseAppHost=false'
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    // Docker Build
                    sh "docker build -t $DOCKER_IMAGE_NAME -f Dockerfile ."
                }
            }
        }

        stage('Push image') {
            steps {
                script {
                    // Docker Push with specific tag
                    withDockerRegistry([credentialsId: DOCKER_REGISTRY_CREDENTIALS, url: '']) {
                        docker.withRegistry('https://registry.hub.docker.com', DOCKER_REGISTRY_CREDENTIALS) {
                            dockerImage.push("backend-serkan:latest")
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'CI/CD pipeline completed successfully!'
        }

        failure {
            echo 'CI/CD pipeline failed!'
        }
    }
}
